name: Test

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Test
        run: make test